CREATE DATABASE chatroom;

CREATE TABLE conversation(chat_id SERIAL PRIMARY KEY, sender VARCHAR(30) NOT NULL, receiver VARCHAR(30) NOT NULL, date DATE NOT NULL, time TIME WITH TIME ZONE NOT NULL, STATUS BOOLEAN NOT NULL, ip VARCHAR(30) NOT NULL, os VARCHAR(15) NOT NULL);

CREATE TABLE reply(reply_id SERIAL PRIMARY KEY, chat_id SMALLINT, message TEXT NOT NULL, FOREIGN KEY(chat_id) REFERENCES conversation(chat_id));

ALTER SEQUENCE conversation_chat_id_seq RESTART WITH 10001;
ALTER SEQUENCE reply_reply_id_seq RESTART WITH 20001;
